tasks:
  - name: setup-astra
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      gp open README.md
      cd /workspace/workshop-betterreads/tools
      wget https://downloads.datastax.com/enterprise/cqlsh-astra.tar.gz \
          && tar xvzf cqlsh-astra.tar.gz \
          && rm -f cqlsh-astra.tar.gz
      curl -OL https://downloads.datastax.com/dsbulk/dsbulk-1.8.0.tar.gz \
          && tar xvzf dsbulk-1.8.0.tar.gz \
          && rm -f dsbulk-1.8.0.tar.gz
      clear
      echo "Initializing the environment, please wait..."
      cd /workspace/workshop-betterreads
      nvm install 16.11.1
      npm install -g npm@latest
      npm install astra-setup
      chmod 700 /workspace/workshop-betterreads/cqlsh
    command: |
      clear
      cd /workspace/workshop-betterreads
      npm exec astra-setup workshops better_reads
      clear
      set -a
      source .env
      set +a
      env | grep ASTRA
      cd /workspace/workshop-betterreads/better-reads-webapp
      mvn test -Dtest=io.javabrains.betterreads.Test01_Connectivity.java
ports:
  - port: 5005
  - port: 8080
    onOpen: open-browser
    visibility: public
  
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    # Datastax Astra PLugin
    - datastax.astra-for-vs-code
    # Extension Pack for Java
    - vscjava.vscode-java-pack
    # Extension Pack for Spring boot
    - Pivotal.vscode-boot-dev-pack
   
