
spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.a9958b0f68563669
            client-secret: 41655317cc2302b59792654751682e7e6e2817cd
  data:
    cassandra:
      schema-action: create-if-not-exists

astra:
  api:
    application-token: AstraCS:gdZaqzmFZszaBTOlLgeecuPs:edd25600df1c01506f5388340f138f277cece2c93cb70f4b5fa386490daa5d44
    database-id: 3ed83de7-d97f-4fb6-bf9f-82e9f7eafa23
    database-region: eu-west-1
  cql:
    enabled: true
    driver-config:
      basic:
        session-keyspace: better_reads
      advanced:
        connection:
          init-query-timeout: 10s


