server:
  port: 8080
  error:
    include-stacktrace: always
    
spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.cf8b7bc35ce335cb
            client-secret: 947c56fff66d6019b0361931e4dee6e687a6fb8a
  data:
    cassandra:
      schema-action: create-if-not-exists

datadump.location:
  works: src/test/resources/test-works.txt
  #authors: src/test/resources/test-authors.txt
  authors: /Users/cedricklunven/Downloads/ol_dump_authors_2021-11-30.txt
  
astra:
  api:
    application-token: AstraCS:gdZaqzmFZszaBTOlLgeecuPs:edd25600df1c01506f5388340f138f277cece2c93cb70f4b5fa386490daa5d44
    database-id: 3ed83de7-d97f-4fb6-bf9f-82e9f7eafa23
    database-region: eu-west-1
  cql:
    enabled: true
    driver-config:
      basic:
        session-keyspace: better_reads
      advanced:
        connection:
          init-query-timeout: 10s


